[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/2025-1/10/"
to = "/agenda/2025/10/"

[[redirects]]
from = "/raphaele-dumas/"
to = "/les-cineastes/raphaele-dumas/"

[[redirects]]
from = "/agenda/2025-1/03/"
to = "/agenda/2025/03/"

[[redirects]]
from = "/agenda/2025-1/01/"
to = "/agenda/2025/01/"

[[redirects]]
from = "/agenda/2025-1/11/"
to = "/agenda/2025/11/"

[[redirects]]
from = "/categories/adherentes/"
to = "/les-cineastes/categories/membres/"

[[redirects]]
from = "/agenda/2025-1/06/"
to = "/agenda/2025/06/"

[[redirects]]
from = "/agenda/2025-1/02/"
to = "/agenda/2025/02/"

[[redirects]]
from = "/annuaire/"
to = "/les-cineastes/"

[[redirects]]
from = "/jean-charles-leyris/"
to = "/les-cineastes/jean-charles-leyris/"

[[redirects]]
from = "/agenda/2025-01-28-test-evenement/"
to = "/agenda/2025/test-evenement/"

[[redirects]]
from = "/agenda/2025-1/09/"
to = "/agenda/2025/09/"

[[redirects]]
from = "/2025-01-24-sortie-du-dernier-film/"
to = "/actualites/2025-01-24-sortie-du-dernier-film/"

[[redirects]]
from = "/agenda/2025-1/12/"
to = "/agenda/2025/12/"

[[redirects]]
from = "/equipe/"
to = "/les-cineastes/"

[[redirects]]
from = "/actualites-des-films/"
to = "/les-cineastes/actualites-des-films/"

[[redirects]]
from = "/films/1968-les-premices/"
to = "/films/1915-les-premices/"

[[redirects]]
from = "/agenda/2025-1/05/"
to = "/agenda/2025/05/"

[[redirects]]
from = "/elodie-boin-zanchi/"
to = "/les-cineastes/elodie-boin-zanchi/"

[[redirects]]
from = "/projets/"
to = "/films/"

[[redirects]]
from = "/actions/"
to = "/films/"

[[redirects]]
from = "/agenda/2025-1/"
to = "/agenda/2025/"

[[redirects]]
from = "/categories/membres/"
to = "/les-cineastes/categories/membres/"

[[redirects]]
from = "/elodie-boin-zanchi/actualites/"
to = "/les-cineastes/elodie-boin-zanchi/actualites/"

[[redirects]]
from = "/les-cineastes/actualite-des-films/"
to = "/les-cineastes/actualites-des-films/"

[[redirects]]
from = "/actions/1968-les-premices/"
to = "/films/1915-les-premices/"

[[redirects]]
from = "/actus-des-films/"
to = "/actualites/actus-des-films/"

[[redirects]]
from = "/agenda/2025-1/04/"
to = "/agenda/2025/04/"

[[redirects]]
from = "/2025-01-24-sortie-du-dernier-film-1/"
to = "/actualites/2025-01-24-sortie-du-dernier-film-1/"

[[redirects]]
from = "/les-cineastes/categories/adherentes/"
to = "/les-cineastes/categories/membres/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/les-cineastes/equipe-editoriale/"

[[redirects]]
from = "/claire-marty/"
to = "/les-cineastes/claire-marty/"

[[redirects]]
from = "/equipe-editoriale/"
to = "/les-cineastes/equipe-editoriale/"

[[redirects]]
from = "/agenda/2025-1/07/"
to = "/agenda/2025/07/"

[[redirects]]
from = "/agenda/2025-1/08/"
to = "/agenda/2025/08/"

[[redirects]]
from = "/annuaire/equipe-editoriale/"
to = "/les-cineastes/equipe-editoriale/"

